### ISSUE TITLE
Error: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by Vadorequest** [marvinpinto/actions#65] opened 2021-01-24 15:34 UTC
Surprisingly, this action which used to work started to fail today, using v1.1.0 (using sha).

```
Generating changelog
  Found 1 pull request(s) associated with commit 234cefd9e510cd6db5ef9d1d9bed6f882d8b2363
  Error: Cannot read property 'trim' of undefined
  (node:2477) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined
      at e.exports (/home/runner/work/_actions/marvinpinto/action-automatic-releases/10bdce64abdb4558a2ee6983192242be40d631d8/dist/index.js:1:562792)
      at Function.e.exports.sync (/home/runner/work/_actions/marvinpinto/action-automatic-releases/10bdce64abdb4558a2ee6983192242be40d631d8/dist/index.js:1:561270)
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/10bdce64abdb4558a2ee6983192242be40d631d8/dist/index.js:1:211488
      at Generator.next (<anonymous>)
      at s (/home/runner/work/_actions/marvinpinto/action-automatic-releases/10bdce64abdb4558a2ee6983192242be40d631d8/dist/index.js:1:210383)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  (node:2477) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:2477) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![image](https://user-images.githubusercontent.com/3807458/105635171-f0386b00-5e61-11eb-9c42-53d95d573d69.png)

**Comment by Vadorequest** [comment] 2021-01-24 15:49
Somehow, this happened because I had pushed a branch which has the same name as another branch I had used recently. I believe the remote branch had been deleted though and I don't see how it relates.

But, renaming my local branch and pushing on a new remote branch with the same changes but different branch name fixed it.

Sounds like this is an edge case. Still, I'll leave the issue open as it might be better covered and yield a more descriptive error message 😃

**Comment by eyal0** [comment] 2021-01-29 21:31
I have this problem, too.  My branch is "master" and I never had this problem before!

**Comment by eyal0** [comment] 2021-01-29 21:35
It's hard for me to debug it because the error message points into a javascript file that is very compressed.  :-(

Why is that compression a good idea?

**Comment by eyal0** [comment] 2021-01-29 21:39
Related: https://github.com/conventional-changelog/conventional-changelog/issues/691
Related: https://github.com/marvinpinto/actions/issues/20#issuecomment-719964192

**Comment by eyal0** [comment] 2021-01-29 21:55
this ought to fix it: https://github.com/conventional-changelog/conventional-changelog/pull/757

**Comment by eyal0** [comment] 2021-01-29 22:01
I think that it is caused by having a merge commit that is just one line and that one line is just the automatically generated "Merged..." line.

**Comment by Vadorequest** [comment] 2021-01-30 19:33
it might very well be the reason, I also had an issue after a git merge.

**Comment by Vadorequest** [comment] 2021-02-02 10:07
@marvinpinto Any idea how this could be fixed? It systematically fails when merging a PR onto our master branch and breaks our CI.

I'm thinking maybe adding a commit message when merging might fix it, but it's more of a workaround and I'll likely forget about doing it.

**Comment by eyal0** [comment] 2021-02-02 15:36
@Vadorequest The workaround is for you to rebase.  You need to find the merge commit that is only one line of text and add a second line with some text in it.

@marvinpinto cannot fix it because it's in a library.

**Comment by Vadorequest** [comment] 2021-02-03 10:07
If it's a library/dependency I don't see how rebasing could help anyhow, IMHO it's to the lib author (marvinpinto) to update the lib being used by this project. But he can't do that until your PR at https://github.com/conventional-changelog/conventional-changelog/pull/757 has been merged.

**Comment by eyal0** [comment] 2021-02-04 17:53
@Vadorequest To be clear, I didn't mean rebasing this repo.  I mean rebasing your own repo so that merge commits have more than one line of non-empty text.

**Comment by Vadorequest** [comment] 2021-02-04 22:01
I totally misunderstood you, thanks for clarifying! Makes total sense, but I can't rebase in my particular case. Adding a merge commit message should also fix it, haven't tried it yet though!

**Comment by marvinpinto** [comment] 2021-03-23 12:56
If I'm understanding this correctly, will updating the conventional commits parser dependency resolve this issue?

**Comment by eyal0** [comment] 2021-03-23 17:20
I think so.

**Comment by Sly777** [comment] 2021-04-15 16:17
Hey @marvinpinto do you have any timeline for this change? For temp solution, I can also create PR for checking trim function on variables (which is not that clean way but it would work 🤷‍♂️)

**Comment by marvinpinto** [comment] 2021-04-15 17:52
@Sly777 Hey there! I updated the conventional commits parser dependency a while back. Could you see if youre still running into this issue using the latest update? You can either use the `@latest` tag or `@<latest sha>` when pinning the dependency version.

Thanks!

**Comment by Vadorequest** [comment] 2021-04-17 08:32
@marvinpinto Thanks for the fix! It's a bit hard to understand what version should be pinned though, because of the mirror and commit messages that aren't descriptive.

https://github.com/marvinpinto/action-automatic-releases/commits/master

I can't tell the difference between those, unlike https://github.com/marvinpinto/actions/commits/master/packages/automatic-releases which is properly documented.

What's the commit for v1.1.1 release?

**Comment by marvinpinto** [comment] 2021-04-17 14:00
@Vadorequest I completely understand how confusing the mirroring among multiple repos can be. This was the only way I could swing it to keep a monorepo (for my sanity) and still publish actions to the GitHub Marketplace.

The semver and `latest` tagged releases are the same across all the repos, e.g. https://github.com/marvinpinto/action-automatic-releases/tree/v1.1.1

Pinning to a sha now gets interesting because one will need the SHA from the mirrored repo itself, and not this one. It would have been nice if GitHub Marketplace supported monorepos for Actions but here we are :shrug:

I'll also cut an updated release sometime this weekend :+1:

**Comment by eyal0** [comment] 2021-04-17 14:17
> the only way I could swing it to keep a monorepo (for my sanity) and still publish actions to the GitHub Marketplace.

Is this because GitHub has a requirement that each repo can only be a single GitHub Action?

That was not a good choice by GitHub.  They could have allowed for multiple actions and multiple entrypoints in a single repo and it would have solved the problem.  :-(

**Comment by Vadorequest** [comment] 2021-04-17 15:14
> @Vadorequest I completely understand how confusing the mirroring among multiple repos can be. This was the only way I could swing it to keep a monorepo (for my sanity) and still publish actions to the GitHub Marketplace.

I don't mind the mirroring itself, I understand you did it this way for a good reason. Maybe improving the mirror commit messages would help track what they relate to? Could you add a link to the origin commit as description maybe? This would be enough for tracability.

We're pinning to SHA because it's better from a security standpoint (security audits are pointless, otherwise). See https://github.com/UnlyEd/next-right-now/discussions/223 for details.

**Comment by marvinpinto** [comment] 2021-04-25 15:09
I cut a new tagged release with all the updates from the last little while, which should resolve this issue. Please open a new issue if something related comes up :heart:

**Closed by marvinpinto** 2021-04-25 15:09 UTC
Labels: automatic-releases, bug
