### ISSUE TITLE
changelog too large fail this action

### ISSUE THREAD

**Issue by wenytang-ms-123** [marvinpinto/actions#255] opened 2021-08-06 07:48 UTC
It's really an awesome action! 
sometimes changelog may be manual work, so will it support changelog from file or skip add changelog
we meets an error shows that changelog overdue 25000 so this action failed as following
![image](https://user-images.githubusercontent.com/76087945/128476482-a76bfcd1-09b8-4d9c-8f39-e993400a510f.png)

**Comment by wenytang-ms-123** [comment] 2021-08-06 08:06
https://github.com/OfficeDev/TeamsFx/runs/3239123093?check_suite_focus=true

**Comment by wenytang-ms-123** [comment] 2021-08-06 08:17
associate issue 
https://github.com/marvinpinto/actions/issues/19

**Comment by frank-w** [comment] 2021-08-11 18:34
I also facing the 25000 char issue (linux fork). Looks like the changelog is the cause.

Is there any workaround? Currently build on every push is failing

**Comment by wenytang-ms-123** [comment] 2021-08-13 01:53
> I also facing the 25000 char issue (linux fork). Looks like the changelog is the cause.
> 
> Is there any workaround? Currently build on every push is failing

my workaround is moving the latest tag, but it's sucks.

**Comment by frank-w** [comment] 2021-08-14 15:09
I do not use static tags,because i build for different branches.

i'm not sure which start is used for changelog

https://github.com/frank-w/BPI-R2-4.14/blob/97092a62e3ca7242c36b13fac3ee59f9a3ef7a52/.github/workflows/build.yml#L81

**Comment by wenytang-ms** [comment] 2021-08-19 01:31
> I do not use static tags,because i build for different branches.
> 
> i'm not sure which start is used for changelog
> 
> https://github.com/frank-w/BPI-R2-4.14/blob/97092a62e3ca7242c36b13fac3ee59f9a3ef7a52/.github/workflows/build.yml#L81

seems you resolved it

**Comment by frank-w** [comment] 2021-08-19 06:16
I use another upload-acrion for 5.4 and 5.10 tree as a workaround

**Comment by marvinpinto** [comment] 2021-09-02 20:21
Duplicate of https://github.com/marvinpinto/actions/pull/124

**Closed by marvinpinto** 2021-09-02 20:21 UTC
