### ISSUE TITLE
Generating changelog: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by robinvanpoppel** [marvinpinto/actions#20] opened 2020-04-04 08:20 UTC
Hi,

I was trying out this action on [this workflow](https://github.com/victor-rds/KeeTrayTOTP/runs/560065082) and got an error during the generation of the changelog. This was the first time running this action. Prior to running it, I tagged `0f47f15ad738972fe7104645639aceb3da94aa21` as latest to reduce the number of commits taken into account for the changelog. 

```
Generating changelog
  Adding commit "Bump MSTest.TestFramework from 2.0.0 to 2.1.0" to the changelog
  Adding commit "Bump Microsoft.NET.Test.Sdk from 16.4.0 to 16.5.0" to the changelog
  ##[error]Cannot read property 'trim' of undefined
  (node:3432) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined
      at e.exports (D:\a\_actions\marvinpinto\action-automatic-releases\latest\dist\index.js:1:572296)
      at Function.e.exports.sync (D:\a\_actions\marvinpinto\action-automatic-releases\latest\dist\index.js:1:570888)
      at D:\a\_actions\marvinpinto\action-automatic-releases\latest\dist\index.js:1:222656
      at Generator.next (<anonymous>)
      at s (D:\a\_actions\marvinpinto\action-automatic-releases\latest\dist\index.js:1:221551)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  (node:3432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:3432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by marvinpinto** [comment] 2020-04-04 12:18
Hey @robinvanpoppel! Could you enable [debug](https://github.com/marvinpinto/actions#debugging) logging on that build? I suspect it's getting stuck [somewhere in this function](https://github.com/marvinpinto/actions/blob/bb681da2f82883571023ffba1456c13737834bca/packages/automatic-releases/src/utils.ts#L107-L142) but I'm not certain.

I'll try and have a look at this sometime next week.

**Comment by robinvanpoppel** [comment] 2020-04-05 06:53
@marvinpinto, thanks for your quicky reply. I was not aware of the debug option. Thanks for pointing that out :)

The project containing this action was not mine, so I do not have access to the settings. I did try reproducing it my own fork. Unfortunately this did not happen over there. 
I retagged a later commit in [the original repository](https://github.com/victor-rds/KeeTrayTOTP) , but the release now succeeds there as well. I'll update this issue if I experience it again.

**Comment by marvinpinto** [comment] 2020-04-05 13:08
Sounds great, I'll close this for now but re-open if need be :+1:

**Closed by marvinpinto** 2020-04-05 13:08 UTC
Labels: bug

**Comment by Async0x42** [comment] 2020-05-07 19:54
I've been getting a similar error from a pull-request for sharepointplus-loader, using dependabot.

Here's the trimmed debug for the relevant portion, let me know if you need anything else:

```
 ##[debug]Searching for pull requests associated with commit dc4b8e6e40624f59f645775899e9ec52f851a7f0
  ##[debug] request {"method":"GET","baseUrl":"https://api.github.com","headers":{"accept":"application/vnd.github.groot-preview+json","user-agent":"octokit.js/16.33.0 Node.js/12.13.1 (Linux 5.0; x64)","authorization":"token ***"},"mediaType":{"format":"","previews":[]},"request":{"validate":{"commit_sha":{"required":true,"type":"string"},"owner":{"required":true,"type":"string"},"page":{"type":"integer"},"per_page":{"type":"integer"},"repo":{"required":true,"type":"string"}}},"url":"/repos/:owner/:repo/commits/:commit_sha/pulls","owner":"Async0x42","repo":"collaborative-sharepoint-calendar","commit_sha":"dc4b8e6e40624f59f645775899e9ec52f851a7f0"}
  ##[debug] GET /repos/Async0x42/collaborative-sharepoint-calendar/commits/dc4b8e6e40624f59f645775899e9ec52f851a7f0/pulls - 200 in 234ms
  Found 1 pull request(s) associated with commit dc4b8e6e40624f59f645775899e9ec52f851a7f0
  ##[debug]Changelog options: {"parserOpts":{"headerPattern":{},"headerCorrespondence":["type","scope","subject"],"noteKeywords":["BREAKING CHANGE"],"revertPattern":{},"revertCorrespondence":["header","hash"]},"mergePattern":"^Merge pull request #(.*) from (.*)$","mergeCorrespondence":["issueId","source"]}
  ##[error]Cannot read property 'trim' of undefined
  (node:4476) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined
      at e.exports (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:572296)
      at Function.e.exports.sync (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:570888)
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:222656
      at Generator.next (<anonymous>)
      at s (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:221551)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  (node:4476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:4476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  ##[debug]Node Action run completed with exit code 1
  ##[debug]Finishing: Run marvinpinto/action-automatic-releases@latest
```

**Comment by robinvanpoppel** [comment] 2020-05-08 13:49
If it helps: in our repo we also use dependabot, so it might have to do with that, though I haven't experienced it ever since.

**Comment by vasek-b** [comment] 2020-10-12 15:48
I'm having the same issue, it fails on the merge commit for dependabot pull request. Just an idea, I'm not sure if it might be related or not, but the original branch that dependabot created is deleted.

**Comment by svsool** [comment] 2020-10-31 17:34
Got the same problem https://github.com/svsool/vscode-memo/runs/1336434985.

**Comment by Vadorequest** [comment] 2021-02-02 10:12
@marvinpinto This issue should be re-opened until https://github.com/conventional-changelog/conventional-changelog/pull/757 is merged (related to https://github.com/conventional-changelog/conventional-changelog/issues/691)

Also, https://github.com/marvinpinto/actions/issues/65 is a duplicate of this issue.
